### ISSUE TITLE
TO BE DONE BEFORE STABLE RELEASE: style design

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/earthkit-plots#50]
### Is your feature request related to a problem? Please describe.

We need to implement the following features for the style before the stable release:

- We should be able to create multiple identities using some of the same keys and select the identity with the higher matching score with the data.
- We should be able to put multiple values in the keys (typically model levels, pressure levels, etc.)
- New structure for the styles: one file for all the styles and another file for matching identities

For instance for styles.yml:
```
MEAN_SEA_LEVEL_PRESSURE_IN_PA:
  type: Contour
  linecolors: "#33334d"
  linewidths: [0.5, 0.5, 0.5, 1]
  labels: true
  levels:
    step: 400
  units: Pa
  legend_style: null

MEAN_SEA_LEVEL_PRESSURE_IN_HPA:
  type: Contour
  linecolors: "#33334d"
  linewidths: [0.5, 0.5, 0.5, 1]
  labels: true
  levels:
    step: 4
  units: hPa
  legend_style: null

SOIL_WETNESS_INDEX_GREENS:
  type: Style    
  colors: [white, lime, green, darkgreen]
  levels: [0, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1]
  extend: max
```
and then match.yml
```
mean-sea-level-pressure:
    optimal: MEAN_SEA_LEVEL_PRESSURE_IN_HPA
    styles:
        - MEAN_SEA_LEVEL_PRESSURE_IN_PA
        - MEAN_SEA_LEVEL_PRESSURE_IN_HPA
```
